### ISSUE TITLE
[NPUZeroInitStructsHolder] zeContextDestroy failed 0X78000001

### ISSUE THREAD

**Issue by helloyanis** [openvinotoolkit/openvino.genai#2068]
Hi there!

I'm trying to generate an image with my NPU but failing to do so. Using GPU and CPU work fine.

hello_query_device/hello_query_device.py) output : 
```
PS C:\Users\me> openvino_env\Scripts\activate
(openvino_env) PS C:\Users\me> py hello_query_device.py
[ INFO ] Available devices:
[ INFO ] CPU :
[ INFO ]        SUPPORTED_PROPERTIES:
[ INFO ]                AVAILABLE_DEVICES:
[ INFO ]                RANGE_FOR_ASYNC_INFER_REQUESTS: 1, 1, 1
[ INFO ]                RANGE_FOR_STREAMS: 1, 14
[ INFO ]                EXECUTION_DEVICES: CPU
[ INFO ]                FULL_DEVICE_NAME: Intel(R) Core(TM) Ultra 7 155U
[ INFO ]                OPTIMIZATION_CAPABILITIES: FP32, INT8, BIN, EXPORT_IMPORT
[ INFO ]                DEVICE_TYPE: Type.INTEGRATED
[ INFO ]                DEVICE_ARCHITECTURE: intel64
[ INFO ]                NUM_STREAMS: 1
[ INFO ]                INFERENCE_NUM_THREADS: 0
[ INFO ]                PERF_COUNT: False
[ INFO ]                INFERENCE_PRECISION_HINT: <Type: 'float32'>
[ INFO ]                PERFORMANCE_HINT: PerformanceMode.LATENCY
[ INFO ]                EXECUTION_MODE_HINT: ExecutionMode.PERFORMANCE
[ INFO ]                PERFORMANCE_HINT_NUM_REQUESTS: 0
[ INFO ]                ENABLE_CPU_PINNING: True
[ INFO ]                SCHEDULING_CORE_TYPE: SchedulingCoreType.ANY_CORE
[ INFO ]                MODEL_DISTRIBUTION_POLICY: set()
[ INFO ]                ENABLE_HYPER_THREADING: True
[ INFO ]                DEVICE_ID:
[ INFO ]                CPU_DENORMALS_OPTIMIZATION: False
[ INFO ]                LOG_LEVEL: Level.NO
[ INFO ]                CPU_SPARSE_WEIGHTS_DECOMPRESSION_RATE: 1.0
[ INFO ]                DYNAMIC_QUANTIZATION_GROUP_SIZE: 32
[ INFO ]                KV_CACHE_PRECISION: <Type: 'uint8_t'>
[ INFO ]                KEY_CACHE_PRECISION: <Type: 'uint8_t'>
[ INFO ]                VALUE_CACHE_PRECISION: <Type: 'uint8_t'>
[ INFO ]                KEY_CACHE_GROUP_SIZE: 0
[ INFO ]                VALUE_CACHE_GROUP_SIZE: 0
[ INFO ]
[ INFO ] GPU :
[ INFO ]        SUPPORTED_PROPERTIES:
[ INFO ]                AVAILABLE_DEVICES: 0
[ INFO ]                RANGE_FOR_ASYNC_INFER_REQUESTS: 1, 2, 1
[ INFO ]                RANGE_FOR_STREAMS: 1, 2
[ INFO ]                OPTIMAL_BATCH_SIZE: 1
[ INFO ]                MAX_BATCH_SIZE: 1
[ INFO ]                DEVICE_ARCHITECTURE: GPU: vendor=0x8086 arch=v12.70.4
[ INFO ]                FULL_DEVICE_NAME: Intel(R) Graphics (iGPU)
[ INFO ]                DEVICE_UUID: 8680457d080000000002000000000000
[ INFO ]                DEVICE_LUID: 3632010000000000
[ INFO ]                DEVICE_TYPE: Type.INTEGRATED
[ INFO ]                DEVICE_GOPS: {<Type: 'float16'>: 3993.60009765625, <Type: 'float32'>: 1996.800048828125, <Type: 'int8_t'>: 7987.2001953125, <Type: 'uint8_t'>: 7987.2001953125}
[ INFO ]                OPTIMIZATION_CAPABILITIES: FP32, BIN, FP16, INT8, EXPORT_IMPORT
[ INFO ]                GPU_DEVICE_TOTAL_MEM_SIZE: 7455502336
[ INFO ]                GPU_UARCH_VERSION: 12.70.4
[ INFO ]                GPU_EXECUTION_UNITS_COUNT: 64
[ INFO ]                GPU_MEMORY_STATISTICS: {}
[ INFO ]                PERF_COUNT: False
[ INFO ]                MODEL_PRIORITY: Priority.MEDIUM
[ INFO ]                GPU_HOST_TASK_PRIORITY: Priority.MEDIUM
[ INFO ]                GPU_QUEUE_PRIORITY: Priority.MEDIUM
[ INFO ]                GPU_QUEUE_THROTTLE: Priority.MEDIUM
[ INFO ]                GPU_ENABLE_SDPA_OPTIMIZATION: True
[ INFO ]                GPU_ENABLE_LOOP_UNROLLING: True
[ INFO ]                GPU_DISABLE_WINOGRAD_CONVOLUTION: False
[ INFO ]                CACHE_DIR:
[ INFO ]                CACHE_MODE: CacheMode.OPTIMIZE_SPEED
[ INFO ]                PERFORMANCE_HINT: PerformanceMode.LATENCY
[ INFO ]                EXECUTION_MODE_HINT: ExecutionMode.PERFORMANCE
[ INFO ]                COMPILATION_NUM_THREADS: 14
[ INFO ]                NUM_STREAMS: 1
[ INFO ]                PERFORMANCE_HINT_NUM_REQUESTS: 0
[ INFO ]                INFERENCE_PRECISION_HINT: <Type: 'float16'>
[ INFO ]                ENABLE_CPU_PINNING: False
[ INFO ]                DEVICE_ID: 0
[ INFO ]                DYNAMIC_QUANTIZATION_GROUP_SIZE: 0
[ INFO ]                ACTIVATIONS_SCALE_FACTOR: -1.0
[ INFO ]                WEIGHTS_PATH:
[ INFO ]                CACHE_ENCRYPTION_CALLBACKS: UNSUPPORTED TYPE
[ INFO ]                KV_CACHE_PRECISION: <Type: 'undefined'>
[ INFO ]
[ INFO ] NPU :
[ INFO ]        SUPPORTED_PROPERTIES:
[ INFO ]                AVAILABLE_DEVICES: 3720
[ INFO ]                CACHE_DIR:
[ INFO ]                COMPILATION_NUM_THREADS: 14
[ INFO ]                DEVICE_ARCHITECTURE: 3720
[ INFO ]                DEVICE_GOPS: {<Type: 'bfloat16'>: 0.0, <Type: 'float16'>: 5734.39990234375, <Type: 'float32'>: 0.0, <Type: 'int8_t'>: 11468.7998046875, <Type: 'uint8_t'>: 11468.7998046875}
[ INFO ]                DEVICE_ID:
[ INFO ]                DEVICE_LUID: d936010000000000
[ INFO ]                DEVICE_PCI_INFO: {domain: 0 bus: 0 device: 0xb function: 0}
[ INFO ]                DEVICE_TYPE: Type.INTEGRATED
[ INFO ]                DEVICE_UUID: 80d1d11eb73811eab3de0242ac130004
[ INFO ]                ENABLE_CPU_PINNING: False
[ INFO ]                EXECUTION_DEVICES: NPU
[ INFO ]                EXECUTION_MODE_HINT: ExecutionMode.PERFORMANCE
[ INFO ]                FULL_DEVICE_NAME: Intel(R) AI Boost
[ INFO ]                INFERENCE_PRECISION_HINT: <Type: 'float16'>
[ INFO ]                LOG_LEVEL: Level.ERR
[ INFO ]                MODEL_PRIORITY: Priority.MEDIUM
[ INFO ]                NPU_BYPASS_UMD_CACHING: False
[ INFO ]                NPU_COMPILATION_MODE_PARAMS:
[ INFO ]                NPU_COMPILER_DYNAMIC_QUANTIZATION: False
[ INFO ]                NPU_COMPILER_VERSION: 458754
[ INFO ]                NPU_DEFER_WEIGHTS_LOAD: False
[ INFO ]                NPU_DEVICE_ALLOC_MEM_SIZE: 0
[ INFO ]                NPU_DEVICE_TOTAL_MEM_SIZE: 8589934592
[ INFO ]                NPU_DRIVER_VERSION: 1003967
[ INFO ]                NPU_MAX_TILES: 2
[ INFO ]                NPU_TILES: -1
[ INFO ]                NPU_TURBO: False
[ INFO ]                NUM_STREAMS: 1
[ INFO ]                OPTIMAL_NUMBER_OF_INFER_REQUESTS: 1
[ INFO ]                OPTIMIZATION_CAPABILITIES: FP16, INT8, EXPORT_IMPORT
[ INFO ]                PERFORMANCE_HINT: PerformanceMode.LATENCY
[ INFO ]                PERFORMANCE_HINT_NUM_REQUESTS: 1
[ INFO ]                PERF_COUNT: False
[ INFO ]                RANGE_FOR_ASYNC_INFER_REQUESTS: 1, 10, 1
[ INFO ]                RANGE_FOR_STREAMS: 1, 4
[ INFO ]                WORKLOAD_TYPE: WorkloadType.DEFAULT
[ INFO ]
```

The command above doesn't throw any error.

I have used [this model](https://huggingface.co/GraydientPlatformAPI/indigo-furry-120) (got it by git cloning it), then ran this command from the [Openvino GenAI readme](https://github.com/openvinotoolkit/openvino.genai?tab=readme-ov-file#performing-image-generation) to convert it.

```ps1
optimum-cli export openvino --model .\indigo-furry-120\ --weight-format int8 --dataset conceptual_captions .\indigo-furry-120INT8\ --task stable-diffusion
```

However, running this modified version of GenAI's [text2image.py](https://github.com/openvinotoolkit/openvino.genai/blob/master/samples/python/image_generation/text2image.py) :

```py
#!/usr/bin/env python3
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

import argparse

import openvino_genai
from PIL import Image

from colorama import Fore, Back, Style

import time

import random


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('model_dir')
    parser.add_argument('prompt')
    parser.add_argument('negative_prompt')
    args = parser.parse_args()

    device = 'NPU'  # CPU, GPU can be used as well
    pipe = openvino_genai.Text2ImagePipeline(args.model_dir, device)

    # Set the seed for reproducibility
    seed = random.randint(0, 2**32 - 1)

    print(Fore.GREEN + f'Using seed: {seed}')
    print(Fore.CYAN + f'Prompt: {args.prompt}')
    print(Fore.YELLOW + f'Negative prompt: {args.negative_prompt}')
    print(Style.RESET_ALL)
    print('Generating image...')
    image_tensor = pipe.generate(
        args.prompt,
        negative_prompt=args.negative_prompt,
        width=800,
        height=800,
        num_inference_steps=45,
        num_images_per_prompt=1,
        rng_seed=seed)

    image = Image.fromarray(image_tensor.data[0])
    filename = f"images/image_{int(time.time())}_{int(seed)}.bmp"
    image.save(filename)
    print(Fore.GREEN + f'Image saved as {filename}')
    print(Style.RESET_ALL)

if '__main__' == __name__:
    main()
```

Throws this error

```
Traceback (most recent call last):
  File "C:\Users\me\text2img.py", line 51, in <module>
    main()
  File "C:\Users\me\text2img.py", line 25, in main
    pipe = openvino_genai.Text2ImagePipeline(args.model_dir, device)
RuntimeError: Exception from src\inference\src\cpp\core.cpp:112:
Exception from src\inference\src\dev\plugin.cpp:53:
Exception from src\plugins\intel_npu\src\plugin\src\plugin.cpp:750:
Exception from src\plugins\intel_npu\src\compiler_adapter\src\ze_graph_ext_wrappers.cpp:361:
L0 pfnCreate2 result: ZE_RESULT_ERROR_INVALID_ARGUMENT, code 0x78000004 - generic error code for invalid arguments . Bounds are not provided for shape [-9223372036854775808, -9223372036854775808, 768] that has dynamic dimensions




[ERROR] 09:06:12.765 [NPUZeroInitStructsHolder] zeContextDestroy failed 0X78000001
```

The same error is thrown as well with the regular text2image.py from this repository.

I tried to open an issue in the openvino repository but they redirected me here, see below :

> Hi @helloyanis 
> 
> Since this is a separate issue, I suggest you open a new issue on [openvino.genai GitHub](https://github.com/openvinotoolkit/openvino.genai/issues). 

 _Originally posted by @zulkifli-halim in [#29668](https://github.com/openvinotoolkit/openvino/issues/29668#issuecomment-2797624648)_

I hope this can help, thanks!

**Comment by AsyaPronina** [comment]
Hello! Actually this sample might not work with NPU. For NPU the following sample exists: https://github.com/openvinotoolkit/openvino.genai/blob/master/samples/python/image_generation/heterogeneous_stable_diffusion.py
It can run StableDiffusion and LCM models on NPU or heterogeneously.
@RyanMetcalfeInt8

**Comment by helloyanis** [comment]
Hi! I tried this sample but I had trouble changing the image size, putting anything other than 512x512 wouldn't start the generation.

That's a bit off-topic and not a help forum so one issue at a time, 

I could succesfully generate a 512x512 image with this sample. However after generating the image, it crashed with the same error `zeContextDestroy failed 0X78000001` (While the image was correctly generated and accessible through files)

I'm away from my PC right now but I can send you the output from that sample tomorrow if you'd like?

**Comment by RyanMetcalfeInt8** [comment]
Hi @helloyanis, which version of OpenVINO GenAI & NPU driver do you have installed? I would highly recommend:
* Latest release of OpenVINO GenAI (2025.1)
* Latest NPU Driver from [here](https://www.intel.com/content/www/us/en/download/794734/intel-npu-driver-windows.html) (.3967)

And absolutely, can send the log with size other than 512x512 (is it 800x800, as per your above code?)?

As for the `zeContextDestroy failed 0X78000001`, I'm pretty sure that this issue was resolved as part of OpenVINO 2025.1 release (hence my above recommendations).

Finally, do you know what stable diffusion model architecture [this model](https://huggingface.co/GraydientPlatformAPI/indigo-furry-120) uses? From the model_index.json there, it seems like it's based on SD1.5, but I wasn't too sure. If you are still seeing issues, it would be interesting to see if it also fails with this model: https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5

Thanks!
Ryan

**Comment by helloyanis** [comment]
Hi! I have updated my NPU driver and OpenVINO GenAI to these versions and now I have another error when using this heterogeneous generation script :

```py
#!/usr/bin/env python3
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

import argparse

import openvino_genai

import random

import time

from PIL import Image

from colorama import Fore, Style

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('model_dir')
    parser.add_argument('prompt')
    parser.add_argument('negative_prompt')

    # Set devices to command-line args if specified, otherwise default to CPU.
    # Note that these can be set to CPU, GPU, or NPU.
    parser.add_argument('text_encoder_device', nargs='?', default='NPU')
    parser.add_argument('unet_device', nargs='?', default='NPU')
    parser.add_argument('vae_decoder_device', nargs='?', default='NPU')

    args = parser.parse_args()

    width = 512
    height = 512
    number_of_images_to_generate = 1
    number_of_inference_steps_per_image = 45

    print(f"text_encoder_device = {args.text_encoder_device}")
    print(f"unet_device = {args.unet_device}")
    print(f"vae_decoder_device = {args.vae_decoder_device}")
    # Set the seed for reproducibility
    seed = random.randint(0, 2**32 - 1)
    print(Fore.GREEN + f'Using seed: {seed}')
    print(Fore.CYAN + f'Prompt: {args.prompt}')
    print(Fore.YELLOW + f'Negative prompt: {args.negative_prompt}')

    # this is the path to where compiled models will get cached
    # (so that the 'compile' method run much faster 2nd+ time)
    ov_cache_dir = "./cache"

    #
    # Step 1: Create the initial Text2ImagePipeline, given the model path
    #
    print(Style.RESET_ALL)
    print('Creating pipeline... (Step 1/4)')
    pipe = openvino_genai.Text2ImagePipeline(args.model_dir)

    #
    # Step 2: Reshape the pipeline given number of images, height, width, and guidance scale.
    #
    print('Reshaping pipeline... (Step 2/4)')
    pipe.reshape(1, height, width, pipe.get_generation_config().guidance_scale)

    #
    # Step 3: Compile the pipeline given the specified devices, and properties (like cache dir)
    #
    properties = {"CACHE_DIR": ov_cache_dir}

    # Note that if there are device-specific properties that are needed, they can
    # be added using a "DEVICE_PROPERTIES" entry, like this:
    #properties = {
    #    "DEVICE_PROPERTIES":
    #    {
    #        "CPU": {"CACHE_DIR": "cpu_cache"},
    #        "GPU": {"CACHE_DIR": "gpu_cache"},
    #        "NPU": {"CACHE_DIR": "npu_cache"}
    #    }
    #}
    print('Compiling pipeline... (Step 3/4)')
    pipe.compile(args.text_encoder_device, args.unet_device, args.vae_decoder_device, config=properties)

    #
    # Step 4: Use the Text2ImagePipeline to generate 'number_of_images_to_generate' images.
    #
    print(Style.RESET_ALL)
    print('Generating image... (Step 4/4)')
    for imagei in range(0, number_of_images_to_generate):
        image_tensor = pipe.generate(
            args.prompt,
            negative_prompt=args.negative_prompt,
            num_inference_steps=number_of_inference_steps_per_image,
            num_images_per_prompt=1,
            rng_seed=seed,
        )

        image = Image.fromarray(image_tensor.data[0])
        filename = f"images/image_{int(time.time())}_{int(seed)}.bmp"
        image.save(filename)
        print(Fore.GREEN + f'Image saved as {filename}')
        print(Style.RESET_ALL)


if '__main__' == __name__:
    main()
```

It indeed works without any error!
```ps1
(openvino_env) PS C:\Users\me> py .\scripts\heterogeneous_stable_diffusion.py ".\indigo-furry-120INT8\" 'Wolf, sitting, forest, night sky, by_metalowl' 'signature'
text_encoder_device = NPU
unet_device = NPU
vae_decoder_device = NPU
Using seed: 1800088782
Prompt: Wolf, sitting, forest, night sky, by_metalowl
Negative prompt: signature

Creating pipeline... (Step 1/4)
C:\Users\me\openvino_env\lib\site-packages\openvino\runtime\__init__.py:10: DeprecationWarning: The `openvino.runtime` module is deprecated and will be removed in the 2026.0 release. Please replace `openvino.runtime` with `openvino`.
  warnings.warn(
Reshaping pipeline... (Step 2/4)
Compiling pipeline... (Step 3/4)

Generating image... (Step 4/4)
Image saved as images/image_1744960214_1800088782.bmp
```

So that is fixed, thanks for the update!

However, changing this in the script

```diff
- width = 512
- height = 512
+ width = 800
+ height = 800
```
Throws the following error

```ps1
(openvino_env) PS C:\Users\me> py .\scripts\heterogeneous_stable_diffusion.py ".\indigo-furry-120INT8\" 'Wolf, sitting, forest, night sky, by_metalowl' 'signature'
text_encoder_device = NPU
unet_device = NPU
vae_decoder_device = NPU
Using seed: 483119452
Prompt: Wolf, sitting, forest, night sky, by_metalowl
Negative prompt: signature

Creating pipeline... (Step 1/4)
C:\Users\me\openvino_env\lib\site-packages\openvino\runtime\__init__.py:10: DeprecationWarning: The `openvino.runtime` module is deprecated and will be removed in the 2026.0 release. Please replace `openvino.runtime` with `openvino`.
  warnings.warn(
Reshaping pipeline... (Step 2/4)
Compiling pipeline... (Step 3/4)

Generating image... (Step 4/4)
Traceback (most recent call last):
  File "C:\Users\me\scripts\heterogeneous_stable_diffusion.py", line 102, in <module>
    main()
  File "C:\Users\me\scripts\heterogeneous_stable_diffusion.py", line 86, in main
    image_tensor = pipe.generate(
RuntimeError: Exception from src\inference\src\cpp\infer_request.cpp:245:
Exception from src\plugins\intel_npu\src\utils\src\zero\zero_wrappers.cpp:182:
L0 zeCommandQueueExecuteCommandLists result: ZE_RESULT_ERROR_DEVICE_LOST, code 0x70000001 - device hung, reset, was removed, or driver update occurred
```

I haven't yet tried with SD 1.5, I'll let you know once I did.

Since this is not the same issue, would you like me to create another issue and close this one?

**Comment by RyanMetcalfeInt8** [comment]
> Since this is not the same issue, would you like me to create another issue and close this one?

I'm okay keeping with you just keeping it as the same issue for now.

As for the issue with 800x800, could you also try 832x832?

**Comment by helloyanis** [comment]
Yes, still having the same issue. After a long time to load to compile the pipeline, it starts generating the image and instantly crashes with the exact same log.

**Comment by RyanMetcalfeInt8** [comment]
Got it, and just to double check -- does it work for:
```
text_encoder_device=NPU
unet_device=NPU
vae_decoder_device=GPU
```

and as a sanity check, does it work in this configuration?
```
text_encoder_device=GPU
unet_device=GPU
vae_decoder_device=GPU
```

**Comment by helloyanis** [comment]
The following does NOT work and gives the same error :
```
text_encoder_device=NPU
unet_device=NPU
vae_decoder_device=GPU
```
But the following DOES work 👍 
```
text_encoder_device=GPU
unet_device=GPU
vae_decoder_device=GPU
```
Trying to do dome extra testing, and the following settings
```
text_encoder_device=GPU
unet_device=GPU
vae_decoder_device=NPU
```
seems to turn off my screen??

It goes to step 4 then the screen shuts off (I'm on a laptop so can't check if there's no signal)

I can recover by hard-resetting my PC (holding the power button) but this seems like a very very strange bug

**Comment by helloyanis** [comment]
Updating to the latest version of the Python script seems to have fixed the bug
