### ISSUE TITLE
Qwen3-embedding-8B can't run on NPU, but Qwen3-embedding-0.6B can run successfully

### ISSUE THREAD

**Issue by jilongW** [openvinotoolkit/openvino.genai#3161]
Qwen3-embedding-8B can't run on NPU, but Qwen3-embedding-0.6B can run successfully

Error for Qwen3-embedding-8B
```
root@edgeaihost31:~/models/openvino.genai/tools/llm_bench# python3 benchmark.py -m /root/models/OpenVINO/Qwen3-embedding-8B-int4-cw-ov -n 2 --task text_embed -bs 1 --embedding_max_length 128  -d NPU
Multiple distributions found for package optimum. Picked distribution: optimum-intel
/usr/local/lib/python3.12/dist-packages/torch/amp/autocast_mode.py:270: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn(
[ INFO ] ==SUCCESS FOUND==: use_case: text_embed, model_type: qwen3, model_Name: Qwen3-embedding-8B-int4-cw-ov
[ INFO ] OV Config={'CACHE_DIR': ''}
[ INFO ] Model path=/root/models/OpenVINO/Qwen3-embedding-8B-int4-cw-ov, openvino runtime version: 2025.4.1-20426-82bbf0292c5-releases/2025/4, genai version: 2025.4.1.0-2683-fc593653d77
[ INFO ] Selected OpenVINO GenAI for benchmarking
[ INFO ] Pipeline initialization time: 44.96s
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!
[ INFO ] [warm-up][P0] Input text: intranatal Ceratophyllum urd orthogonal hypomeral rickstaddle prescriptively theriotheism superpassage matachina pseudopious undigitated Uds aerolith pennatularian bullydom moggan enchantingly unenraged unfreeze scazon Kaskaskia overshine irrepentance dijudicate sageship niter vessignon semilined wieldable teneral differencingly multichrome mesovarian pleochroism Karaite mayoress mousing xyst fibrocellular Woolwa preantiquity epigonous busybodyish noncontent ineradicableness Macflecknoe recollective podginess obtruncate rohuna earnestly cyke Xenurus wheelswarf terminize fletcher Hebrewdom ensnarement hypostasize historicodogmatic cerebrogalactose dysacousis buckleless carney omnivorousness bodge procerebrum unblaming Juglans crotin proconfession chirotonsory arsenicize hostage allwhither immit infranatural unafflicted twitty psychodiagnostics misknow reminder obviator ceratotheca trainagraph shad flintily fruticose flounder unbasket fishweed aquatint unslothful foremisgiving unequiva ... [truncated to 1024]
[ ERROR ] An exception occurred
[ INFO ] Traceback (most recent call last):
  File "/root/models/openvino.genai/tools/llm_bench/benchmark.py", line 320, in main
    iter_data_list, pretrain_time, iter_timestamp = CASE_TO_BENCH[model_args['use_case'].task](
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/models/openvino.genai/tools/llm_bench/task/text_embeddings.py", line 190, in run_text_embddings_benchmark
    text_emb_fn(input_text, num, model, tokenizer, args, iter_data_list, p_idx, bench_hook, proc_id, mem_consumption)
  File "/root/models/openvino.genai/tools/llm_bench/task/text_embeddings.py", line 120, in run_text_embeddings_genai
    model.embed_documents(input_text_list)
RuntimeError: Exception from src/inference/src/cpp/infer_request.cpp:246:
Exception from src/plugins/intel_npu/src/utils/src/zero/zero_wrappers.cpp:112:
L0 pfnAppendGraphExecute result: ZE_RESULT_ERROR_UNKNOWN, code 0x7ffffffe - an action is required to complete the desired operation .
```

Log for Qwen3-embedding-0.6B
```
root@edgeaihost31:~/models/openvino.genai/tools/llm_bench#  python3 benchmark.py -m /root/models/OpenVINO/Qwen3-embedding-0.6B-int4-cw-ov -n 2 --task text_embed -bs 1 --embedding_max_length 128  -d NPU
Multiple distributions found for package optimum. Picked distribution: optimum-intel
/usr/local/lib/python3.12/dist-packages/torch/amp/autocast_mode.py:270: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn(
[ INFO ] ==SUCCESS FOUND==: use_case: text_embed, model_type: qwen3, model_Name: Qwen3-embedding-0.6B-int4-cw-ov
[ INFO ] OV Config={'CACHE_DIR': ''}
[ INFO ] Model path=/root/models/OpenVINO/Qwen3-embedding-0.6B-int4-cw-ov, openvino runtime version: 2025.4.1-20426-82bbf0292c5-releases/2025/4, genai version: 2025.4.1.0-2683-fc593653d77
[ INFO ] Selected OpenVINO GenAI for benchmarking
[ INFO ] Pipeline initialization time: 10.66s
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!
[ INFO ] [warm-up][P0] Input text: objectable demonstrative towniness individuity druid staylessness unstooping Hanukkah unbroad facioscapulohumeral Kentia fainly retrocopulant perfervent ghastliness decidua oligemia reclaim seemingly counterpicture paletot sudoresis antichrist Temanite reburden plateasm understaff isospore forbiddenness testamental updome overbillow Panamanian daffish alkalimeter postamniotic nondiphthongal Ovibovinae Ailuropus internalness exiguous brownout attributable panoram nonarmigerous Annard hydroglider aditus nonslaveholding interscribe aortal bisulphite iguaniform isorhodeose microzoon censurableness bareca acrobat gomlah Amphicondyla conicity beadleism Gymnostomata endocardiac Megachilidae iliopubic antipatheticalness missyish uredinology refrigerator consignificate turnoff unapprobation Nicol dissociability brushmaking burnet hemoglobiniferous unparceling bracteose divarication fog shisn brewing deport forbiddingly washshed chondropterygious Phillis flub irrefrangible bination cashable li ... [truncated to 1024]
[ INFO ] [warm-up][P0] Input token size: 1466, Infer count: 1, Tokenization Time: 5.03ms, Generation Time: 0.12s, Latency: 0.1203 ms/prompt
[ INFO ] [warm-up][P0] First iteration latency: 120.25 ms, other iterations latency: NA, len of input tokens: 1466 * 1
[ INFO ] [warm-up][P0] First infer latency: 120.25 ms, other infers latency: NA, inference count: 1
[ INFO ] [warm-up][P0] start: 2026-01-04T02:40:11.977354, end: 2026-01-04T02:40:12.103385
[ INFO ] [1][P0] Input token size: 1466, Infer count: 1, Tokenization Time: 5.60ms, Generation Time: 0.07s, Latency: 0.0666 ms/prompt
[ INFO ] [1][P0] First iteration latency: 66.65 ms, other iterations latency: NA, len of input tokens: 1466 * 1
[ INFO ] [1][P0] First infer latency: 66.65 ms, other infers latency: NA, inference count: 1
[ INFO ] [1][P0] start: 2026-01-04T02:40:12.103490, end: 2026-01-04T02:40:12.176354
[ INFO ] [2][P0] Input token size: 1466, Infer count: 1, Tokenization Time: 6.55ms, Generation Time: 0.05s, Latency: 0.0523 ms/prompt
[ INFO ] [2][P0] First iteration latency: 52.33 ms, other iterations latency: NA, len of input tokens: 1466 * 1
[ INFO ] [2][P0] First infer latency: 52.33 ms, other infers latency: NA, inference count: 1
[ INFO ] [2][P0] start: 2026-01-04T02:40:12.176433, end: 2026-01-04T02:40:12.235957
[ INFO ] <<< Warm-up iteration is excluded. >>>
[ INFO ] [Total] Iterations: 2
[ INFO ] [Average] P[0] Input token size: 1466, 1st iteration latency: 59.49 ms, 2nd iteration latency: NA, 2nd iteration throughput: NA
```

ENV:
```
openvino                                 2025.4.1
openvino-genai                           2025.4.1.0
openvino-telemetry                       2025.2.0
openvino-tokenizers                      2025.4.1.0
optimum                                  2.0.0
optimum-intel                            1.27.0.dev0+46557e9
optimum-onnx                             0.0.3

NPU Driver:     https://github.com/intel/linux-npu-driver/releases/tag/v1.28.0
```
Convert model:
```
optimum-cli export openvino OpenVINO/Qwen3-embedding-8B-int4-cw-ov  --framework pt --task feature-extraction --weight-format int4 --sym --group-size 128 --weight-format int4 --sym --group-size -1 --ratio 1 --trust-remote-code --model Qwen/Qwen3-Embedding-8B
optimum-cli export openvino OpenVINO/Qwen3-embedding-0.6B-int4-cw-ov  --framework pt --task feature-extraction --weight-format int4 --sym --group-size 128 --weight-format int4 --sym --group-size -1 --ratio 1 --trust-remote-code --model Qwen/Qwen3-Embedding-0.6B
```

Running command:
```
cd openvino.genai/tools/llm_bench
python3 benchmark.py -m /root/models/OpenVINO/Qwen3-embedding-0.6B-int4-cw-ov -n 2 --task text_embed -bs 1 --embedding_max_length 128  -d NPU
python3 benchmark.py -m /root/models/OpenVINO/Qwen3-embedding-8B-int4-cw-ov -n 2 --task text_embed -bs 1 --embedding_max_length 128  -d NPU
```

**Comment by as-suvorov** [comment]
@jilongW Do you have same issue with CPU device?

**Comment by jilongW** [comment]
@as-suvorov Hi, No issue on CPU
```
root@edgeaihost31:~/models/openvino.genai/tools/llm_bench# python3 benchmark.py -m /root/models/OpenVINO/Qwen3-embedding-8B-int4-cw-ov -n 2 --task text_embed -bs 1 --embedding_max_length 128  -d CPU
Multiple distributions found for package optimum. Picked distribution: optimum-intel
/usr/local/lib/python3.12/dist-packages/torch/amp/autocast_mode.py:270: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn(
[ INFO ] ==SUCCESS FOUND==: use_case: text_embed, model_type: qwen3, model_Name: Qwen3-embedding-8B-int4-cw-ov
[ INFO ] OV Config={'CACHE_DIR': ''}
[ WARNING ] It is recommended to set the environment variable OMP_WAIT_POLICY to PASSIVE, so that OpenVINO inference can use all CPU resources without waiting.
[ INFO ] The num_beams is 1, update Torch thread num from 24 to 12, avoid to use the CPU cores for OpenVINO inference.
[ INFO ] Model path=/root/models/OpenVINO/Qwen3-embedding-8B-int4-cw-ov, openvino runtime version: 2025.4.1-20426-82bbf0292c5-releases/2025/4, genai version: 2025.4.1.0-2683-fc593653d77
[ INFO ] Selected OpenVINO GenAI for benchmarking
[ INFO ] Pipeline initialization time: 4.23s
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!
[ INFO ] [warm-up][P0] Input text: Hydrus immonastered culottic Latinitaster inference anbury varicellate parliamentarism even bronchotomy unhardily couching nonpractice nuchal Chimariko Galbulae chinchilla unobese sedgelike garb clerically perfecting pharmacopsychology parlay thanker trimestrial undazing disquiparancy unorbital supercommercial accubitum Tremellales acetylcarbazole nematocerous ephemeran resourceless teloteropathy wise dispiece dingily congruist atraumatic weightedly bountifully oversweet chirotonsory consignatary pielet threadless springerle expertness estipulate essentiality irrigate laparocolostomy iguanian unwelcomed menstrual beech lucubratory inapplicableness midmandibular rebend ammoresinol kampong forfeit saccharocolloid hymenopterologist khagiarite thyroprotein resultive commissar thiocyano bechase genarch legibility vincibleness foresign sensuist synthronos riverwise Baronga circumflexion esthesiology pugilistically philomathematical canions apishness scala infra linchpin unglossily extendib ... [truncated to 1024]
[ INFO ] [warm-up][P0] Input token size: 1440, Infer count: 1, Tokenization Time: 4.31ms, Generation Time: 0.72s, Latency: 0.7242 ms/prompt
[ INFO ] [warm-up][P0] First iteration latency: 724.17 ms, other iterations latency: NA, len of input tokens: 1440 * 1
[ INFO ] [warm-up][P0] First infer latency: 724.17 ms, other infers latency: NA, inference count: 1
[ INFO ] [warm-up][P0] start: 2026-01-08T01:57:46.772915, end: 2026-01-08T01:57:47.501716
[ INFO ] [1][P0] Input token size: 1440, Infer count: 1, Tokenization Time: 1.87ms, Generation Time: 0.79s, Latency: 0.7874 ms/prompt
[ INFO ] [1][P0] First iteration latency: 787.42 ms, other iterations latency: NA, len of input tokens: 1440 * 1
[ INFO ] [1][P0] First infer latency: 787.42 ms, other infers latency: NA, inference count: 1
[ INFO ] [1][P0] start: 2026-01-08T01:57:47.501753, end: 2026-01-08T01:57:48.291302
[ INFO ] [2][P0] Input token size: 1440, Infer count: 1, Tokenization Time: 1.91ms, Generation Time: 0.85s, Latency: 0.8533 ms/prompt
[ INFO ] [2][P0] First iteration latency: 853.26 ms, other iterations latency: NA, len of input tokens: 1440 * 1
[ INFO ] [2][P0] First infer latency: 853.26 ms, other infers latency: NA, inference count: 1
[ INFO ] [2][P0] start: 2026-01-08T01:57:48.291331, end: 2026-01-08T01:57:49.146782
[ INFO ] <<< Warm-up iteration is excluded. >>>
[ INFO ] [Total] Iterations: 2
[ INFO ] [Average] P[0] Input token size: 1440, 1st iteration latency: 820.34 ms, 2nd iteration latency: NA, 2nd iteration throughput: NA
```

**Comment by Zulkifli-Intel** [comment]
Hi @jilongW 
The issue with the Qwen3-embedding-8B model cannot run on NPU has been resolved on the latest [OpenVINO GenAI Nightly Build ](https://docs.openvino.ai/2025/get-started/install-openvino.html?PACKAGE=OPENVINO_GENAI&VERSION=NIGHTLY&OP_SYSTEM=LINUX&DISTRIBUTION=PIP). Below is the result from my test:

```
(openvino_nightly_env) 3161$ python openvino.genai/tools/llm_bench/benchmark.py -m OpenVINO/Qwen3-embedding-8B-int4-cw-ov -n 2 --task text_embed -bs 1 --embedding_max_length 128  -d NPU
Multiple distributions found for package optimum. Picked distribution: optimum
/home/user/openvino_nightly_env/lib/python3.12/site-packages/diffusers/models/transformers/transformer_kandinsky.py:168: UserWarning: CUDA is not available or torch_xla is imported. Disabling autocast.
  @torch.autocast(device_type="cuda", dtype=torch.float32)
/home/user/openvino_nightly_env/lib/python3.12/site-packages/diffusers/models/transformers/transformer_kandinsky.py:272: UserWarning: CUDA is not available or torch_xla is imported. Disabling autocast.
  @torch.autocast(device_type="cuda", dtype=torch.float32)
[ INFO ] ==SUCCESS FOUND==: use_case: text_embed, model_type: qwen3, model_Name: Qwen3-embedding-8B-int4-cw-ov
[ INFO ] OV Config={'CACHE_DIR': ''}
[ INFO ] Model path=OpenVINO/Qwen3-embedding-8B-int4-cw-ov, openvino runtime version: 2026.1.0-21058-cd2cfd3e308, genai version: 2026.1.0.0-2864-511c9328943
The tokenizer you are loading from 'OpenVINO/Qwen3-embedding-8B-int4-cw-ov' with an incorrect regex pattern: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503/discussions/84#69121093e8b480e709447d5e. This will lead to incorrect tokenization. You should set the `fix_mistral_regex=True` flag when loading this tokenizer to fix this issue.
[ INFO ] Selected OpenVINO GenAI for benchmarking
[ INFO ] Pipeline initialization time: 20.29s
The tokenizer you are loading from 'OpenVINO/Qwen3-embedding-8B-int4-cw-ov' with an incorrect regex pattern: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503/discussions/84#69121093e8b480e709447d5e. This will lead to incorrect tokenization. You should set the `fix_mistral_regex=True` flag when loading this tokenizer to fix this issue.
[ INFO ] [warm-up][P0] Input text: What is OpenVINO?
[ INFO ] [warm-up][P0] Input token size: 7, Infer count: 1, Tokenization Time: 2.43ms, Generation Time: 0.52s, Latency: 0.5204 ms/prompt
[ INFO ] [warm-up][P0] First iteration latency: 520.39 ms, other iterations latency: NA, len of input tokens: 7 * 1
[ INFO ] [warm-up][P0] First infer latency: 520.39 ms, other infers latency: NA, inference count: 1
[ INFO ] [warm-up][P0] start: 2026-02-10T22:44:33.582550, end: 2026-02-10T22:44:34.108415
[ INFO ] [1][P0] Input token size: 7, Infer count: 1, Tokenization Time: 0.23ms, Generation Time: 0.28s, Latency: 0.2824 ms/prompt
[ INFO ] [1][P0] First iteration latency: 282.39 ms, other iterations latency: NA, len of input tokens: 7 * 1
[ INFO ] [1][P0] First infer latency: 282.39 ms, other infers latency: NA, inference count: 1
[ INFO ] [1][P0] start: 2026-02-10T22:44:34.108448, end: 2026-02-10T22:44:34.391259
[ INFO ] [2][P0] Input token size: 7, Infer count: 1, Tokenization Time: 0.19ms, Generation Time: 0.28s, Latency: 0.2762 ms/prompt
[ INFO ] [2][P0] First iteration latency: 276.17 ms, other iterations latency: NA, len of input tokens: 7 * 1
[ INFO ] [2][P0] First infer latency: 276.17 ms, other infers latency: NA, inference count: 1
[ INFO ] [2][P0] start: 2026-02-10T22:44:34.391295, end: 2026-02-10T22:44:34.667781
[ INFO ] <<< Warm-up iteration is excluded. >>>
[ INFO ] [Total] Iterations: 2
[ INFO ] [Average] P[0] Input token size: 7, 1st iteration latency: 279.28 ms, 2nd iteration latency: NA, 2nd iteration throughput: NA
```

Please try and let us know if you encounter any issues.

**Comment by Zulkifli-Intel** [comment]
The issue has been fixed. Closing this issue, open a new issue if you have further questions.
